---
title: "01. workflow"
output: word_document
date: "`r Sys.Date()`"
---

#Exploratory analysis ---

```{r}
library(readxl)
library(FactoMineR)
library(factoextra)
library(cluster)
library(tidyverse)
library(patchwork)
library(viridis)
library(GGally)
library(janitor)
theme_set(theme_light())
set.seed(2024)
```

```{r}
df <- read_excel("Hoisesti.xlsx", sheet = "RSD<10")
df <- as_tibble(df) |> 
  mutate_if(is.character, as.factor) |> 
  mutate_if(is.double, as.numeric)
  
df <- df |> as_tibble()

df[,1:2] <- lapply(df[,1:2], as.factor)
df <- df |> 
  unite("Proba_Tip", TIP:SAMPLE, sep = "_", remove = F) |> 
  column_to_rownames("Proba_Tip") |> 
  unite("Proba_Tip", TIP:SAMPLE, sep = "_", remove = F)

  df_check_point <- df


```

##Exploratory analysis in view of clustering ---

```{r}
ggpairs(df, columns = 4:14) +
  ggtitle("Grafic 1. Analiza Exploratorie inițială") +
  theme(strip.background = element_rect(colour = "black", fill = "black"), strip.text.x = element_text(colour = "white", face = "bold"))

```



```{r}
library(dbscan)
lof_scores <- dbscan::lof(scale(df[,4:14], center = T, scale = T), minPts = 10)
summary(lof_scores)
df$lof_scores <- lof_scores
ggplot(df, aes(x = 1:nrow(df), y = lof_scores)) +
  geom_point() + 
  geom_text(aes(label = Proba_Tip)) +
  theme_light() +
  xlab(label = "") +
  ylab(label = "Scorul Densității Locale") +
  ggtitle("Grafic 2. Identificarea valorilor extreme")
```


```{r}
threshold <- 2

df$outlier <- ifelse(lof_scores > threshold, "Valori Extreme", "Inlier")

df <- filter(df, !df$outlier == "Valori Extreme")

ggpairs(df, columns = 4:14, showStrips = T) +
  ggtitle("Grafic 3. Analiza Exploratorie după eliminarea valorilor extreme")+
    theme(strip.background = element_rect(colour = "black", fill = "black"), strip.text.x = element_text(colour = "white", face = "bold"))


```


#Clusters

```{r}
gradient_col <- list(low = "black", mid = "white",high = "red")

df_centr <- as.data.frame(scale(df[,4:14])
                          )

library(hopkins)
hopkins::hopkins(df_centr, m = nrow(df) - 2)

fviz_dist(dist(df_centr), show_labels = T) +
  labs(title = "Grafic 4. Tendințe de grupare",
       subtitle = "Indice Hopkins: 0.959638") 

library(clValid)
library(psych)
distance_matrix <- distance(df_centr)

distance_matrix <- as.matrix(distance_matrix)

internal_validation <- clValid(distance_matrix, 2:8, 
                               clMethods = c("agnes"),
                               validation = c("internal", "stability"))

summary(internal_validation)

```


```{r}
clust_df <- eclust(df_centr,
                               FUNcluster = "agnes",
                               k = 2,
                               hc_metric = "minkowski",
                               hc_method = "ward.D2"
                               )

dendro <- fviz_dend(clust_df) +
  labs(title = "Grafic 5. Dendrograma") +
  theme_light()

dendro

export_clus <- clust_df$cluster
df$clusters <- as.factor(export_clus)


```


#Permutation test for analisys of variance to verify clustering results

```{r}
library(lmPerm)

model_elements <- aovp(scale(cbind(Al2O4_avg, SiO3_avg, K2O_avg, Ca_avg, Ti_avg, Mn_avg, Fe_avg, Zn_avg, Rb_avg, Sr_avg, Zr_avg), scale = F) ~ clusters,
             seqs = F,
             maxIter = 1e6,
             data = df, 
             perm = "Exact")

summary.lmp(model_elements)
summary.aovp(model_elements)



str_resid <- rstandard(model_elements)
#Al204
qqnorm(str_resid[,1], main="qq-plot of residuals Al2O4")
qqline(str_resid[,1])

plot(resid(model_elements)[,1]~fitted(model_elements)[,1], 
    main="Residuals vs Fitted for Al2O4", xlab="fitted", ylab="residuals")
lines(lowess(resid(model_elements)[,1]~fitted(model_elements)[,1]), col="red")

plot(str_resid[,1]~lm.influence(model_elements)$hat, xlab="Leverage", ylab="residuals",
       main="Residuals vs Leverage for Al2O4")
  lines(lowess(str_resid[,1]~lm.influence(model_elements)$hat), col="red")
  
#SiO3  
qqnorm(str_resid[,2], main="qq-plot of residuals SiO3")
qqline(str_resid[,2])

plot(resid(model_elements)[,2]~fitted(model_elements)[,2], 
    main="Residuals vs Fitted for SiO3", xlab="fitted", ylab="residuals")
lines(lowess(resid(model_elements)[,2]~fitted(model_elements)[,2]), col="red")

plot(str_resid[,2]~lm.influence(model_elements)$hat, xlab="Leverage", ylab="residuals",
       main="Residuals vs Leverage for SiO3")
lines(lowess(str_resid[,2]~lm.influence(model_elements)$hat), col="red")

#K2O 
qqnorm(str_resid[,3], main="qq-plot of residuals K2O")
qqline(str_resid[,3])

plot(resid(model_elements)[,3]~fitted(model_elements)[,3], 
    main="Residuals vs Fitted for K2O", xlab="fitted", ylab="residuals")
lines(lowess(resid(model_elements)[,3]~fitted(model_elements)[,3]), col="red")

plot(str_resid[,3]~lm.influence(model_elements)$hat, xlab="Leverage", ylab="residuals",
       main="Residuals vs Leverage for K2O")
  lines(lowess(str_resid[,3]~lm.influence(model_elements)$hat), col="red")

```


#PCA with clusters overlay

```{r}
pca_res <- PCA(df[,4:14], graph = FALSE, scale.unit = T)
summary(pca_res)


plot_pca <- fviz_cluster(clust_df, 
             geom = "point",
             repel = T,
             main = "Grafic 7. Proiecția PCA cu indicarea clusterelor",
            legend.title = "Clustere") + 
  geom_text(label = df$Proba_Tip, hjust = 0.5, nudge_y = -0.09, check_overlap = TRUE)

plot_pca


```

######PCA - visualisations - eigen values
```{r}
eigen_values <- pca_res$eig |> 
  as_tibble() |> 
  rownames_to_column() |> 
    janitor::clean_names() |> 
  arrange(desc(percentage_of_variance)) 


graph_eigen <- eigen_values |> 
    top_n(8, percentage_of_variance) |>
  mutate(percentage_of_variance = round(percentage_of_variance, 2)) |> 
  ggplot(aes(rowname, percentage_of_variance)) +
  geom_col() +
  geom_text(aes(label = percentage_of_variance, vjust = 1.5,
              )) +
  xlab(label = "Componente Principale") +
  ylab(label = "Procentajul variației Explicate") +
  labs(title = "Grafic 6. Puterea de explicație a Componentelor Principale Identificate")
graph_eigen
```

######PCA - visualisations - variables
```{r}
contrib_var_selection <- pca_res$var$contrib |> 
  as.data.frame() |> 
  rownames_to_column() |> 
  mutate_if(is.character, as.factor) 

graph_dim1_contrib <- 
  contrib_var_selection |> 
  mutate(rowname = fct_reorder(rowname, Dim.1)) |> 
  ggplot(aes(Dim.1, rowname)) +
  geom_col() +
  xlab(label = "Contribuții la CP 1") +
  ylab(label = "")


graph_dim2_contrib <- 
  contrib_var_selection |> 
  mutate(rowname = fct_reorder(rowname, Dim.2)) |> 
  ggplot(aes(Dim.2, rowname)) +
  geom_col() +
  xlab(label = "Contribuții la CP 2") +
  ylab(label = "")


graph_dim3_contrib <- 
  contrib_var_selection |> 
  mutate(rowname = fct_reorder(rowname, Dim.3)) |> 
  ggplot(aes(Dim.3, rowname)) +
  geom_col() +
  xlab(label = "Contribuții la CP 3") +
  ylab(label = "")

cors_var <- pca_res$var$cor |> 
  as.data.frame() |> 
  rownames_to_column() |> 
  mutate_if(is.character, as.factor) 

graph_dim1_cors <- 
  cors_var |> 
  mutate(rowname = fct_reorder(rowname, Dim.1, .desc = T)) |> 
  ggplot(aes(Dim.1, rowname)) +
  geom_col() +
  theme(axis.text = element_text(size = 9, face = "bold"),
        axis.title = element_text(face = "bold")
        ) + 
  xlab(label = "Corelația Elementelor cu CP 1") +
  ylab(label = "") +
  inset_element(graph_dim1_contrib,
                left = 0.8,
                bottom = 0.55,
                right = 1,
                top = 1)

graph_dim2_cors <- 
  cors_var |> 
  mutate(rowname = fct_reorder(rowname, Dim.2, .desc = T)) |> 
  ggplot(aes(Dim.2, rowname)) +
  geom_col() +
  theme(axis.title = element_text(face = "bold"),
        axis.text = element_text(size = 9, face = "bold")
        ) + 
  xlab(label = "Corelația Elementelor cu CP 2") +
  ylab(label = "") +
  inset_element(graph_dim2_contrib,
                left = 0.8,
                bottom = 0.5,
                right = 1,
                top = 1)


graph_dim3_cors <- 
  cors_var |> 
  mutate(rowname = fct_reorder(rowname, Dim.3, .desc = T)) |> 
  ggplot(aes(Dim.3, rowname)) +
  geom_col() +
  theme(axis.title = element_text(face = "bold"),
        axis.text = element_text(size = 9, face = "bold")
        ) + 
  xlab(label = "Corelația Elementelor cu CP 3") +
  ylab(label = "") +
  inset_element(graph_dim3_contrib,
                left = 0.8,
                bottom = 0.5,
                right = 1,
                top = 1)
```

######PCA - visualisations - cases
```{r}
coord_ind <- 
  pca_res$ind$coord |> 
  as.data.frame() |> 
  mutate_if(is.character, as.factor) |> 
  rownames_to_column() |> 
  as_tibble() |> 
  separate_wider_delim(rowname, delim = "_", 
                       names = c("TIP", "Proba", "Numar"),
                       cols_remove = F)

graph_ind_1 <- coord_ind |> 
  mutate(rowname = fct_reorder(rowname, Dim.1, .desc = T)) |> 
  ggplot(aes(Dim.1, rowname)) +
  geom_col(aes(colour = df$clusters, fill = df$clusters)) +
  theme(legend.position = "inside",
    legend.position.inside = c(1,1),
    legend.justification.inside = c(1,1),
    axis.text = element_text(size = 9, face = "bold"),
    axis.title = element_text(face = "bold")
    ) + 
  xlab(label =  "Corelația Probelor cu CP 1") + 
  ylab(label =  "Probe") +
  scale_fill_viridis(discrete = T) +
  scale_color_viridis_d() +
  guides(fill = guide_legend(title = "Clustere")) +
  guides(color = F)

graph_ind_2 <- coord_ind |> 
  mutate(rowname = fct_reorder(rowname, Dim.2, .desc = T)) |> 
  ggplot(aes(Dim.2, rowname)) +
  geom_col(aes(colour = df$clusters, fill = df$clusters)) +
  theme(legend.position = "inside",
    legend.position.inside = c(1,1),
    legend.justification.inside = c(1,1),
    axis.text = element_text(size = 9, face = "bold"),
    axis.title = element_text(face = "bold")
    ) + 
  xlab(label =  "Corelația Probelor cu CP 2") + 
  ylab(label =  "Probe") +
  scale_fill_viridis(discrete = T) +
  scale_color_viridis_d() +
  guides(fill = guide_legend(title = "Clustere")) +
  guides(color = F)

graph_ind_3 <- coord_ind |> 
  mutate(rowname = fct_reorder(rowname, Dim.3, .desc = T)) |> 
  ggplot(aes(Dim.3, rowname)) +
  geom_col(aes(colour = df$clusters, fill = df$clusters)) +
  theme(legend.position = "inside",
    legend.position.inside = c(1,1),
    legend.justification.inside = c(1,1),
    axis.text = element_text(size = 9, face = "bold"),
    axis.title = element_text(face = "bold")
    ) + 
  xlab(label =  "Corelația Probelor cu CP 3") + 
  ylab(label =  "Probe") +
  scale_fill_viridis(discrete = T) +
  scale_color_viridis_d() +
  guides(fill = guide_legend(title = "Clustere")) +
  guides(color = F)
```

PCA - bring it home
```{r}
graph_CP1 <- graph_dim1_cors / graph_ind_1 +
  plot_annotation(title = "Grafic 8. Definirea clusterelor în funcție de CP 1")
graph_CP2 <- graph_dim2_cors / graph_ind_2 +
  plot_annotation(title = "Grafic 9. Definirea clusterelor în funcție de CP 2")
graph_CP3 <- graph_dim3_cors / graph_ind_3 +
  plot_annotation(title = "Grafic 10. Definirea clusterelor în funcție de CP 3")
graph_CP1
graph_CP2
graph_CP3
```

# Comparative visualisations of clusters

```{r}
library(ggstatsplot)
df_tst <- df |> 
  gather(key = "Element", value = "Concentratie", 4:14) |> 
  filter(!clusters == "Valori Extreme") |> 
  mutate_if(is.character, as.factor) |> 
  unite("Element_Cluster", Element, clusters, sep = "_", remove = F) |> 
  mutate_if(is.character, as.factor)

grouped_ggbetweenstats(data = df_tst, x = clusters, y = Concentratie, grouping.var = Element, 
                       type = "np",
                       ggsignif.args = list(textsize = 2, tip_length = 0.01),
                       p.adjust.method = "bonferroni",
                       #conf.level = NULL,
                       plotgrid.args = list(ncol = 2))

```


# Visualisation of Zr/Ti ratio
```{r}
df_ti_zr <- full_join(df, df_check_point) 
df_ti_zr$clusters <- coalesce(df_ti_zr$clusters, "Valori Extreme")
df_ti_zr$clusters <- as.factor(df_ti_zr$clusters)
df_ti_zr <- df_ti_zr |> as_tibble() 


 df_ti_zr |> 
    filter(!clusters == "Valori Extreme") |> 
    ggplot(aes(x = Ti_avg, y = Zr_avg, colour = clusters, shape = clusters)) +
    geom_point(show.legend = F, size = 3) +
    geom_text(aes(label = SAMPLE), hjust = 0.0009, nudge_y = -0.0001, check_overlap = TRUE, show.legend = F) +
    stat_density2d(bins = 5) +
    geom_point(data = filter(df_ti_zr, clusters == "Valori Extreme"), aes(x = Ti_avg, y = Zr_avg), color = "black", size = 3, show.legend = F) +
    annotate("text", label = "Valoare Extremă", x = 0.425, y = 0.0096, color = "black", size = 4, fontface = "bold") +
    labs(colour = "Clustere",
         title = "Grafic 12. Exprimare grafică a raportului Zr/Ti") +
  scale_colour_brewer(palette = "Dark2")
  
```

