---
title: "01. workflow"
output: word_document
date: "`r Sys.Date()`"
---

#Exploratory analysis

```{r}
library(tidyverse)
library(ggplot2)
library(readxl)
library(widyr)
library(janitor)
library(factoextra)
library(FactoMineR)
library(rgl)
library(viridis)

theme_set(theme_light())

Hoisesti_pXRF <- read_excel("Hoisesti.xlsx", sheet = "RSD<10")
Hoisesti_pXRF <- as_tibble(Hoisesti_pXRF) |> 
  mutate_if(is.character, as.factor) |> 
  mutate_if(is.double, as.numeric)
  
df <- Hoisesti_pXRF |> as_tibble()

View(df)

df_long <- 
  Hoisesti_pXRF |> 
  pivot_longer(
    cols = -c("SAMPLE", "Tip"),
    names_to = "Elemente",
    values_to = "Procentaje"
    ) |> 
  unite("Sample_Element",
        c("SAMPLE", "Elemente"),
        sep = ".",
        remove = F) |> 
  mutate_if(is.character, as.factor) |> 
  as_tibble()

cors <- df_long |> 
  group_by(SAMPLE) |> 
  pairwise_cor(Elemente, Procentaje, sort = TRUE)
  
cors_tibble <- 
  cors |> 
  as_tibble() |> 
  distinct(item1, .keep_all = T) |> 
  unite(Cor_Pairs,
        c(item1, item2),
        sep = "_vs_",
        remove = F
        ) |>
  mutate_if(is.character, as.factor) |> 
  top_n(20, abs(correlation)) |> 
  mutate(Cor_Pairs = fct_reorder(Cor_Pairs, correlation))

  ggplot(cors_tibble, aes(correlation, Cor_Pairs)) +
  geom_point()
```

Exploratory analysis in view of clustering

```{r}
correlations <- cor(df[, 3:13])
library(corrplot)
corrplot(correlations, type = "lower", )
library(PerformanceAnalytics)
chart.Correlation(log10(df[, 3:13]), histogram = T)

pca_df <- df[-23,3:13] |> 
  PCA(scale.unit = T)
summary(pca_df)


eigen_values <- pca_df$eig |> 
  as_tibble() |> 
  rownames_to_column() |> 
  clean_names() |> 
  arrange(desc(percentage_of_variance)) 

eigen_values

 eigen_values |> 
    top_n(4, percentage_of_variance) |> 
  ggplot(aes(rowname, percentage_of_variance)) +
  geom_col()

cors_var <- pca_df$var$cor |> 
  as.data.frame() |> 
  rownames_to_column() |> 
  mutate_if(is.character, as.factor) 

graph_dim1_cors <- 
  cors_var |> 
  mutate(rowname = fct_reorder(rowname, Dim.1)) |> 
  ggplot(aes(Dim.1, rowname)) +
  geom_col()
graph_dim1_cors

graph_dim2_cors <- 
  cors_var |> 
  mutate(rowname = fct_reorder(rowname, Dim.2)) |> 
  ggplot(aes(Dim.2, rowname)) +
  geom_col()
graph_dim2_cors

graph_dim3_cors <- 
  cors_var |> 
  mutate(rowname = fct_reorder(rowname, Dim.3)) |> 
  ggplot(aes(Dim.3, rowname)) +
  geom_col()
graph_dim3_cors
           
contrib_var_selection <- pca_df$var$contrib |> 
  as.data.frame() |> 
  rownames_to_column() |> 
  mutate_if(is.character, as.factor) 

graph_dim1_contrib <- 
  contrib_var_selection |> 
  mutate(rowname = fct_reorder(rowname, Dim.1)) |> 
  ggplot(aes(Dim.1, rowname)) +
  geom_col()
graph_dim1_contrib

graph_dim2_contrib <- 
  contrib_var_selection |> 
  mutate(rowname = fct_reorder(rowname, Dim.2)) |> 
  ggplot(aes(Dim.2, rowname)) +
  geom_col()
graph_dim2_contrib

graph_dim3_contrib <- 
  contrib_var_selection |> 
  mutate(rowname = fct_reorder(rowname, Dim.3)) |> 
  ggplot(aes(Dim.3, rowname)) +
  geom_col()
graph_dim3_contrib


##Contribuții indivizi

contrib_ind <- 
  pca_df$ind |> 
  as.data.frame() |> 
  mutate_if(is.character, as.factor) |> 
  rownames_to_column() |> 
  as_tibble()

contrib_ind |> 
  mutate(rowname = fct_reorder(rowname, coord.Dim.1, .desc = T)) |> 
  ggplot(aes(coord.Dim.1, rowname, fill = df$clusters)) +
  geom_col()

contrib_ind |> 
  mutate(rowname = fct_reorder(rowname, coord.Dim.2, .desc = T)) |> 
  ggplot(aes(coord.Dim.2, rowname, fill = df$clusters)) +
  geom_col()

contrib_ind |> 
  mutate(rowname = fct_reorder(rowname, coord.Dim.3, .desc = T)) |> 
  ggplot(aes(coord.Dim.3, rowname, fill = df$clusters)) +
  geom_col() +
  scale_fill_viridis_d()

```

Clusters

```{r}
library(NbClust)
NbClust(df_log, distance = "manhattan", method = "average")

gradient_col <-  list(low = "black", mid = "white",high = "red")

df_centr <- as.data.frame(scale
                          (df[-2,3:13], 
                            center = TRUE, 
                            scale = TRUE)
                          ) |> 
  as_tibble()

df_log <- as.data.frame(log10(df[-2,3:13])) |> 
  as_tibble()

cluster_tendency_df <- get_clust_tendency(df[-2,3:13], n = 10, gradient = gradient_col)
cluster_tendency_df #0.71

cluster_tendency_df_centr <- get_clust_tendency(df_centr, n = 10, gradient = gradient_col)      
cluster_tendency_df_centr #0.69

cluster_tendency_df_log <- get_clust_tendency(df_log, n = 10, gradient = gradient_col)      
cluster_tendency_df_log #0.77

cluster_tendency_pca <- get_clust_tendency(pca_df$ind$coord[, 1:5], n = 10, gradient = gradient_col)      
cluster_tendency_pca #0.57

set.seed(2024)

clust_df_log <- eclust(df_log,
                        FUNcluster = "pam",
                        k = 3,
                        hc_metric = "euclidian",
                        hc_method = "average"
                        )
fviz_silhouette(clust_df_log)

clust_df_log <- eclust(df_log,
                               FUNcluster = "agnes",
                               k = 5,
                               hc_metric = "spearman",
                               hc_method = "average"
                               )


fviz_silhouette(clust_df_log)
dendrogram_df_test <- fviz_dend(clust_df_log)
dendrogram_df_test
fviz_cluster(clust_df_log, repel = T) +
  theme_light()


export_clus <- clust_df_log$cluster
df <- df[-2,]
df$clusters <- as.factor(export_clus)
View(df)
```

Clusters visualisation

```{r}
graf_pca_ind_clust <- fviz_pca_biplot(pca_df,
                                      axes = c(1,2),
                                      addEllipses = T, 
                                      ellipse.level = 0.65,
                                     col.ind = df$clusters,
                                     col.var = "black",
                                     repel = TRUE,
                                     title = "Overlay of clustering results over PCA",
                                     legend.title = "Clusters")
graf_pca_ind_clust


scores_selection = as.data.frame(pca_df$ind)

plot3d(scores_selection[,1:3], 
       size = 10,
       col = df$clusters)
options(rgl.printRglwidget = TRUE)

text3d(scores_selection[,1:3],
       texts = df$Tip, 
       cex = 1, pos = 3)
text3d(scores_selection[,1:3],
       texts = export_clus, 
       cex = 1, pos = 1)
text3d(scores_selection[,1:3],
       texts = rownames(df_selection), 
       cex = 1, pos = 2)
text3d(pca_final$var$coord[,1:3], 
       texts = rownames(pca_final$var$coord[,1:3]), 
       col = "red", 
       cex = 0.8)

coords <- NULL
for (i in 1:nrow(pca_final$var$coord)) {
  coords <- rbind(coords, 
                  rbind(c(0,0,0),
                        pca_final$var$coord[i,1:3]))
}

lines3d(coords, 
        col = "red", 
        lwd = 1)

rgl.snapshot('3dplot_pca_rare2.png', fmt = 'png')


```


MANOVA and lda to confirm clustering and PCA

```{r}
df_confirmation <-  
  df |> 
  #filter(!clusters %in% c(5,7)) |> 
  dplyr::select(!c(TIP, SAMPLE))
df_confirmation[,1:11] <-  scale(df_confirmation[,1:11])

View(df_confirmation)

manova_results <- manova(cbind(df_confirmation$Al2O4_avg, df_confirmation$SiO3_avg, df_confirmation$K2O_avg, df_confirmation$Ca_avg, df_confirmation$Ti_avg, df_confirmation$Mn_avg, df_confirmation$Fe_avg, df_confirmation$Zn_avg, df_confirmation$Rb_avg, df_confirmation$Sr_avg, df_confirmation$Zr_avg) ~ df_confirmation$clusters, df_confirmation)

summary.aov(manova_results)

library(effectsize)
eta_squared(manova_results) # dacă valoarea este mai mare de 0.14, mărimea efectului este mare


library(MASS)
verification_lda <- lda(df_confirmation$clusters~., df_confirmation, CV = F)
verification_lda

lda_df <- data.frame(
  clusters = df_confirmation[, "clusters"],
  lda = predict(verification_lda)$x
)
lda_df

predict_lda <- predict(verification_lda)

predict_lda_df <- 
  as_tibble(predict_lda$x)

verification_lda_Cross_Valid <- lda(df_confirmation$clusters~., df_confirmation, CV = T)

missclasification_lda <- table(df_confirmation$clusters, predict_lda$class)
sum(diag(missclasification_lda))/sum(missclasification_lda) * 100


missclasification_lda_cross <- table(df_confirmation$clusters, verification_lda_Cross_Valid$class)
sum(diag(missclasification_lda_cross))/sum(missclasification_lda_cross) * 100


plot(verification_lda, dimen = 3)

ggplot(predict_lda_df) +
  geom_point(aes(x = LD1, y = LD2, color = df_confirmation$clusters), size = 4) +
  theme_light()


plot3d(lda_df[,2:4], 
       size = 10,
       col = lda_df$clusters)
options(rgl.printRglwidget = TRUE)

text3d(lda_df[,2:4],
       texts = df$Tip, 
       cex = 1, pos = 3)
text3d(lda_df[,2:4],
       texts = df$SAMPLE, 
       cex = 1, pos = 1)
text3d(scores_selection[,1:3],
       texts = rownames(df_selection), 
       cex = 1, pos = 2)
text3d(pca_df$var$coord[,1:3], 
       texts = rownames(pca_df$var$coord[,1:3]), 
       col = "red", 
       cex = 0.8)

coords <- NULL
for (i in 1:nrow(pca_df$var$coord)) {
  coords <- rbind(coords, 
                  rbind(c(0,0,0),
                        pca_df$var$coord[i,1:3]))
}

lines3d(coords, 
        col = "red", 
        lwd = 1)

rgl.snapshot('3dplot_pca_rare2.png', fmt = 'png')
```

